### ISSUE TITLE
Broken pipeline

### ISSUE THREAD

**Issue by igorcosta** [igorcosta/api_workspace#17]
there's a syntax issue on the ci-cd-pipeline.yml file to trigger it.

the syntax is this

```
on:
  push:
    branches:
      - dev
    
  pull_request:
    branches:
      - main
  tags:
    - "*"

```

To this, that should fix the issue.

```
on:
  push:
    branches:
      - dev
    tags:
      - "**"
  pull_request:
    branches:
      - main
```

Another issue

[Error](https://github.com/igorcosta/api_workspace/actions/runs/9055335584/workflow)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
